version: 1.0.{build}
image: Ubuntu

environment:
  VIDEO_ID: ""
  VIDEO_URL: ""

install:
  - sudo apt-get update -q
  - sudo apt-get install -y ffmpeg python3-pip
  - pip3 install yt-dlp

build_script:
  - echo "Starting download..."
  - mkdir -p downloads
  - cd downloads
  - yt-dlp --format "best" --output "%(id)s.%(ext)s" "$VIDEO_URL"
  - ls -la

test: off

artifacts:
  - path: downloads
